### ISSUE TITLE
Prepare for an upcoming demo

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha#2524]
- [ ] Write a demo script
- [ ] Ensure that basic CLI CRUD-like commands are stable and can be called on a fresh build
- [ ] Check that all access granting commands are available
- [ ] Improve UX for granting access here (https://github.com/hyperledger/iroha/issues/2514)
- [ ] Ensure that each of those commands is documented in a bash guide
- [ ] Record video snippets for an Iroha demo
- [ ] Edit video snippets for internal use
- [ ] Edit video snippets for external use
- [ ] Consider additional design details

**Comment by appetrosyan** [comment]
That's not how epics work.
