### ISSUE TITLE
Match rust tests and the test model

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha#2936]
- [ ] Add Rust test cases on the test model
- [ ] Calculate subjective test coverage
- [ ] Find poorly covered places.

**Comment by astrokov7** [comment]
1. Add test cases on the test model
2. Calculate subjective test coverage

**Comment by appetrosyan** [comment]
Epic needs a bit more clarification, and added issues to `python`, `java` and `js` SDKs, so we can track progress.

**Comment by appetrosyan** [comment]
Need to create issue for Allure integration into Rust.

**Comment by mversic** [comment]
outdated
