### ISSUE TITLE
Nix packaging and infrastructure

### ISSUE THREAD

**Issue by QuentinI** [hyperledger/iroha#3417]
Nix would solve or assist with solving packaging, development environment setup and reproducible builds for Iroha and accompanying WASM blobs.

This is a tracking issue for following sub-tasks (which are currently a rough plan and are subject to change)

- [ ] Provide a basic Nix flake for building Iroha and it's tools (#3415) 
- [ ] Support cross-compilation with Nix
- [ ] Provide a usable `devShell`
- [ ] Use Nix-controlled environment to build WASM blobs (#3416)
- [ ] Document basic usage of Nix-packaged Iroha

Some things that could be potentially done with a workable Nix infrastructure

- Use nix infrastructure in CI?
- Provide a NixOS module for deploying Iroha peer?
- Build Iroha Docker images with Nix?
- …
