### ISSUE TITLE
Bump syn to 2.0

### ISSUE THREAD

**Issue by DCNick3** [hyperledger/iroha#3682]
Recently syn has had a [new major release](https://github.com/dtolnay/syn/releases/tag/2.0.0), and proc macro ecosystem has largely migrated too.

It might be a good idea to update

Update progress:
- [x] `iroha_data_model_derive` (#3882, #3897)
- [x] `iroha_ffi_derive` (#3814, #3830)
- [x] `iroha_schema_derive` (#3759)
- [x] `iroha_primitives_derive` (#3727)
- [x] `iroha_version_derive` (#3727)
- [x] `iroha_derive` (#3727)
- [x] `iroha_telemetry_derive` (#3909, #4168)
- [x] `iroha_futures_derive` (#3911, #3915)
- [x] `iroha_torii_derive` (#4117, #4118)
- [x] ~~`iroha_config_base_derive`~~ will be removed as part of #4161
- [x] `iroha_executor_derive` (#3934, #3935)
- [x] `iroha_core_wasm_codec_derive` (#3943)
